### ISSUE TITLE
Example doesn't seem to work

### ISSUE THREAD

**Issue by brianbruggeman** [bcicen/slacksocket#22]
I used this example:

```
from slacksocket import SlackSocket

token = 'my_token_here'

socket = SlackSocket(token)
msg = socket.send_msg('hi', channel_name='general')
print(msg.sent)
```

I received an error:

```
Traceback (most recent call last):
  File "tmp.py", line 6, in <module>
    msg = socket.send_msg('hi', channel_name='general')
  File "/Users/.../venv3/lib/python3.5/site-packages/slacksocket/client.py", line 141, in send_msg
    self.ws.send(msg.json)
AttributeError: 'SlackSocket' object has no attribute 'ws'    
```

**Comment by bcicen** [comment]
Thanks for pointing this out @brianbruggeman -- it looks like there's a race condition where, on occasion, send_msg could be run before the websocket is completely setup. I'll have a PR together to resolve this shortly.

**Comment by bcicen** [comment]
#23 merged to resolve this; will be included in the next release. Thanks again for your feedback!

**Comment by brianbruggeman** [comment]
Thanks @bcicen !
