### ISSUE TITLE
Cannot import name

### ISSUE THREAD

**Issue by tolgaergin** [bcicen/slacksocket#35]
Error
```
Traceback (most recent call last):
  File "slacksocket.py", line 1, in <module>
    from slacksocket import SlackSocket
  File "/slacksocket.py", line 1, in <module>
    from slacksocket import SlackSocket
ImportError: cannot import name 'SlackSocket'
```

fixed. shame on me :) it was because of the file name

**Comment by bcicen** [comment]
closing :)
